server:
  port: 8080
spring:
  main:
    banner-mode: "off"
api:
  security:
    hmac:
      secret: "dev-hmac-secret"
      time-window-ms: 60000
## OneBusAway Base URL
  base-url: https://page.net
  ## API KEY
  key: "test"
  ## Agency ID
  agency: 1
